ecomsite/ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('shop/', include('shop.urls', namespace='shop')),

]

ecomsite/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('Out_of_stock/', views.Out_of_stock, name='Out_of_stock'),
    path('<int:id>',views.detail,name = 'detail'),
    path('checkout',views.checkout,name ='checkout'),


    # Other URL patterns for the 'shop' app
]

ecomsite/shop/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    title = models.CharField(max_length=200)
    price = models.FloatField()#Calories
    Proteins = models.FloatField()#proteins
    fats = models.FloatField()#fats
    Carbohydrates = models.FloatField()#carbohydrates
    # category = models.CharField(max_length=200)
    description = models.TextField()
    Image = models.CharField(max_length=1000)#storing image URL
    def __str__(self):
        return self.title
class Orders(models.Model):
    items = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    totalquantity = models.IntegerField(max_length=100)
    totalcost = models.IntegerField(max_length=100)

    def __str__(self):
        return self.name

ecomsite/shop/views.py
from django.shortcuts import render,redirect
from .models import Products,Orders
from django.core.paginator import Paginator
# Create your views here.
def index(request):
    product_objects = Products.objects.all()
    #Search Code Starts
    item_name = request.GET.get('item_name')
    if item_name!='' and item_name is not None:
        product_objects = product_objects.filter(title__icontains = item_name)
        if product_objects.exists():
            return render(request, 'shop/index.html', {'product_objects': product_objects})
        else:
            return redirect('Out_of_stock/') 
    #Search Code Ends
    #Paginator Code starts
    paginator = Paginator(product_objects, 6)#display 4 items in a page
    page = request.GET.get('page')#get the current page number from request
    product_objects = paginator.get_page(page)#get the page object from the requested page number
    return render(request,'shop/index.html',{'product_objects':product_objects})


def Out_of_stock(request):
    return render(request, 'shop/stock.html')



def detail(request,id):
    product_object = Products.objects.get(id=id)
    return render(request,'shop/detail.html', {'product_object': product_object})

def checkout(request):
    if request.method == "POST":
        items = request.POST.get('items',"")
        name = request.POST.get('name',"")
        email = request.POST.get('email',"")
        address = request.POST.get('address',"")
        city = request.POST.get('city',"")
        code = request.POST.get('code',"")
        totalquantity = request.POST.get('totalquantity',"")
        totalcost = request.POST.get('totalcost',"")

        order = Orders(items=items,name=name,email=email,address=address,city=city,code=code,totalquantity=totalquantity,totalcost=totalcost)
        order.save()

    return render(request,'shop/checkout.html') 

ecomsite/shop/templates/shop/base.html
<!--Contain all the code which is going to apply for all the templates-->
{% load static%}
<html>
<head>
    <title>Document</title>
    {% comment %} <link rel  ="stylesheet" href = "{% static 'food/style.css'%}"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% comment %} <link rel = "stylesheet" href = "{%static 'shop/base.css'%}"> {% endcomment %}

</head>
<body>
    <div class="container">
        <div class = "row" style = "margin-top : 20px;">
            <div class = "row">
                <div class = "col-md-12 ">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <div class="collapse navbar-collapse" id="navbarNav">
                          <ul class="navbar-nav">
                            <li class="nav-item">
                                {% comment %} <a class="nav-link" href="#">Features</a> {% endcomment %}
                              <a href="{% url 'shop:index' %}" class="btn btn-warning " style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;" href="#">Home</a>
                              </li>
                            <li class="nav-item">
                              {% comment %} <a class="nav-link" href="#">Features</a> {% endcomment %}
                            <a href="{% url 'shop:checkout' %}" class="btn btn-warning mr-2" style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;" href="#">CheckOut</a>
                            </li>
                            <li class="nav-item">
                              {% comment %} <a id = "sunny"class="btn btn-warning" style = "" href="#">Cart(0)</a> {% endcomment %}
                              <button id="sunny" type="button" class="btn btn-warning" data-toggle="popover" data-content="This is the pop-up message" style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;">
                                Cart(0)
                            </button>
                            </li>
                          </ul>
                        </div>
                      </nav>
                </div>
            </div>
        </div>
        <div class = "row" style = "margin-top : 20px;">
            <div class = "col-md-12">
                <form class = "card card-sm">
                    <div class = "card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <a href="{% url 'shop:index' %}" class= style="">
                                <img src="https://media.istockphoto.com/id/822023804/photo/magnified-food-safety.webp?b=1&s=170667a&w=0&k=20&c=oLUaOHa3dYyxdRyVC8MqRTEQCv349JfZUmIi2Gqesh4=" alt="Logo" width="200" height="100">
                            </a>                            
                        </div>
                        <div class = "col">
                            <input type = "search" name = "item_name" placeholder = "search for items" class = "form-control form-control-boarderless ">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-success" type="submit" style="background-color: green;">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        {% block body %}
        {% endblock body %}
</body>
</html>


ecomsite/shop/templates/shop/detail.html
{% extends 'shop/base.html' %}
{% load static %}

<html>
<head>
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'shop/detail.css' %}">
    <style>
        body {
            font-family: 'Lobster', cursive;
        }
        
        .col-md-6 img {
            max-width: 100%;
            height: auto;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .btn-custom {
            font-weight: 300;
            font-family: 'Lobster', cursive;
            color: black;
            margin-right: 5px;
        }
    </style>
</head>
<body>
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{product_object.Image}}">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <table>
                    <tr style="border-bottom: 1px solid #000;">
                        <th style="text-align: left; padding: 8px;">
                            <a href="{% url 'shop:index' %}" class="btn btn-warning btn-custom">Name</a>
                        </th>
                        <th style="text-align: left; padding: 8px;">
                            <a href="{% url 'shop:index' %}" class="btn btn-warning btn-custom">Values</a>
                        </th>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="font-weight: 900; color: black;">Calories</td>
                        <td style="font-weight: 300; color: black;">{{ product_object.price }}</td>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="font-weight: 900; color: black;">Proteins</td>
                        <td style="font-weight: 300; color: black;">{{ product_object.Proteins }}</td>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="font-weight: 900; color: black;">Fats</td>
                        <td style="font-weight: 300; color: black;">{{ product_object.fats }}</td>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="font-weight: 900; color: black;">Carbohydrates</td>
                        <td style="font-weight: 300; color: black;">{{ product_object.Carbohydrates }}</td>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="font-weight: 900; color: black;">Description</td>
                        <td style="font-weight: 300; color: black;">{{ product_object.description }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% endblock body %}
</body>
</html>

ecomsite/shop/templates/shop/index.html
{% comment %} {% extends 'shop/base.html' %} {% endcomment %}
{%load static %}

<html>
<head>
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   
    
</head>
<body>
    {% block body %}
    <div class="container">
        <div class = "row" style = "margin-top : 20px;">
            <div class = "row">
                <div class = "col-md-12 ">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                          <ul class="navbar-nav">
                            <li class="nav-item">
                                {% comment %} <a class="nav-link" href="#">Features</a> {% endcomment %}
                              <a href="{% url 'shop:index' %}" class="btn btn-warning mr-4" style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;" href="#">Home</a>
                              </li>
                            <li class="nav-item">
                              {% comment %} <a class="nav-link" href="#">Features</a> {% endcomment %}
                            <a href="{% url 'shop:checkout' %}" class="btn btn-warning mr-4" style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;" href="#">CheckOut</a>
                            </li>
                            <li class="nav-item">
                              {% comment %} <a id = "sunny"class="btn btn-warning" style = "" href="#">Cart(0)</a> {% endcomment %}
                              <button id="sunny" type="button" class="btn btn-warning mr-4" data-toggle="popover" data-content="This is the pop-up message" style = "font-weight: 300;font-family: 'Lobster', cursive;color:Black;margin-right:5px;">
                                Cart(0)
                            </button>
                            </li>
                          </ul>
                        </div>
                      </nav>
                </div>
            </div>
        </div>
        <div class = "row" style = "margin-top : 20px;">
            <div class = "col-md-12">
                <form class = "card card-sm">
                    <div class = "card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <a href="{% url 'shop:index' %}" class= style="">
                                <img src="https://media.istockphoto.com/id/1249601382/photo/three-toy-shopping-carts-isolated-on-white-e-commerce-concept.jpg?b=1&s=170667a&w=0&k=20&c=F7d_DuJsyugoiV1yjDdYXsaieAqPmNXN2l4vNXwDdCI=" alt="Logo" width="200" height="100">
                            </a>                            
                        </div>
                        <div class = "col">
                            <input type = "search" name = "item_name" placeholder = "search for items" class = "form-control form-control-boarderless ">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-success" type="submit" style="background-color: green;">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            {% for product in product_objects %}
            <div class="col-md-4">
                <div class="card" style = "margin-top:10px ">
                    <!--Product Image-->
                    <img src="{{ product.Image }}" class="card-img-top"  alt="Product Image">
                    <div class="card-body">
                        <!--ProductTitle-->
                        <div  id = "nm{{product.id}}"class="card-title" style = "font-weight: 900;font-family: 'Lobster', cursive;">{{ product.title }}</div>
                        <!--Product Price-->
                        <div id = "price{{product.id}}"class="card-text" style="color: green; font-weight: 300; font-family: 'Lobster', cursive;">
                            {{ product.price }} cal
                        </div>
                        <!--ProductProteins-->
                        <div id = "proteins{{product.id}}"class="card-text" style="color: green; font-weight: 300; font-family: 'Lobster', cursive; visibility: hidden;">
                            {{ product.Proteins }}gm of Protein
                        </div>
                        <!--ProductFats-->
                        <div id = "fat{{product.id}}"class="card-text" style="color: green; font-weight: 300; font-family: 'Lobster', cursive; visibility: hidden;">
                            {{ product.fats }}gm of fat
                        </div>
                        <!--ProductCarbohydrates-->
                        <div id = "carbo{{product.id}}"class="card-text" style="color: green; font-weight: 300; font-family: 'Lobster', cursive; visibility: hidden;">
                            {{ product.Carbohydrates }}gm of carbs
                        </div>
                        <!--Buttons-->
                        <div class = "row">
                            <!--Viewdetails Button-->
                            <div class="col-md-6">
                                <a href="{% url 'shop:detail' id=product.id %}" class="btn btn-warning" style="background-color: green;font-weight: 300;font-family: 'Lobster', cursive;color:White;">ViewDetails</a></br>
                            </div>
                            <!--Ad to cart Button-->
                            <div class="col-md-6">
                                <button id = "{{product.id}}"class="btn atc btn-warning" style="font-weight: 300;font-family: 'Lobster', cursive;color:White;">Add to Cart</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
            {% endfor %}
        </div>
        <div class = "row">
            <div class = "col-md-3 offset-md-4">
                <ul  style = "margin-top : 50px;"class = "pagination">
                    <!-- Starting of Acessing the previous elements-->
                    {%if product_objects.has_previous%}
                    <li class = "page-item">
                        <a class = "page-link"href = "?page={{product_objects.previous_page_number}}">PreviousPage</a>
                    </li>
                    {% endif %}
                    <!-- ending of Acessing the previous elements-->
                    <!--Starting of Acessing the Current ELement-->

                    <!--Ending of Acessing the Current ELement-->
                    <li class = "page-item active">
                        <a class = "page-link"href = "?page={{product_objects.number}}">CurrentPage</a>
                    </li>

                    <!-- Starting of Acessing the Next elements-->
                    {%if product_objects.has_next%}
                    <li class = "page-item">
                        <a class = "page-link" href = "?page={{product_objects.next_page_number}}">NextPage</a>
                    </li>
                    {% endif %}
                    <!-- ending of Acessing the Next elements-->

                </ul>

            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

</body>
<script type = "text/javascript">
    console.log('this is working');
    

    if(localStorage.getItem('cart')==null){// this cart is from localstorage and var cart is the cart that we use in js.
        var cart = {};//here we created a varibale Cart and we use {} to store the id of the Product and quantity of the product
    }
    //if cart contains any items add that items to var cart
    else{
        //cart = localstorage.getItem('cart')
        cart = JSON.parse(localStorage.getItem('cart'));//we use JSON to parse the String and convert it into a JS Object
    }
    $(document).on('click','.atc',function(){
        console.log("The add to cart is clicked");
        var item_id = this.id.toString();
        console.log(item_id);
        //if the item already present in the cart and again when you hit add to cart it should increment
        if(cart[item_id]!=undefined){
            quantity = cart[item_id][2]+1;
            cart[item_id][2] = quantity
            cart[item_id][3] = cart[item_id][3] + parseFloat(document.getElementById("price"+item_id).innerHTML);
            cart[item_id][5] = cart[item_id][5] + parseFloat(document.getElementById("proteins"+item_id).innerHTML);
            cart[item_id][7] = cart[item_id][7] + parseFloat(document.getElementById("fat"+item_id).innerHTML);
            cart[item_id][9] = cart[item_id][9] + parseFloat(document.getElementById("carbo"+item_id).innerHTML);


            //cart[item_id]=cart[item_id]+1;
        }
        //if the item not in the cart now you are adding thaat item in to cart so we assign 1 as there is only one item
        else{
            //cart[item_id]=1;
            quantity = 1;
            name = document.getElementById("nm"+item_id).innerHTML;
            price = parseFloat(document.getElementById("price"+item_id).innerHTML);
            cost = parseFloat(document.getElementById("price"+item_id).innerHTML);
            prots = parseFloat(document.getElementById("proteins"+item_id).innerHTML);
            totalprots = parseFloat(document.getElementById("proteins"+item_id).innerHTML);
            fats = parseFloat(document.getElementById("fat"+item_id).innerHTML);
            totalfats = parseFloat(document.getElementById("fat"+item_id).innerHTML);
            carbos = parseFloat(document.getElementById("carbo"+item_id).innerHTML);
            totalcarbos = parseFloat(document.getElementById("carbo"+item_id).innerHTML);
            cart[item_id]=[name,price,quantity,cost,prots,totalprots,fats,totalfats,carbos,totalcarbos];
        }
        console.log(cart);//upto now we stored the values in var cart now we need to store the values in local storage
        localStorage.setItem('cart',JSON.stringify(cart));
        document.getElementById("sunny").innerHTML = "Cart("+Object.keys(cart).length+")"
        console.log(Object.keys(cart).length)
    });
    $(document).ready(function() {
        $('[data-toggle="popover"]').popover({
            trigger: 'hover',
            placement: 'bottom'
        });
    });
</script>
{% endblock body %}
</html>

ecomsite/shop/templates/shop/stock.html
{% extends 'shop/base.html' %}
{%load static %}


<html>
    <head>
        {% comment %} <link rel="stylesheet" href="{% static 'shop/stock.css' %}"> {% endcomment %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
        <link rel = "stylesheet" href = "{%static 'shop/index.css'%}">
    
    </head>
    <body>
        {% block body %}
        <h2 class="card-title" style="font-weight: 900; font-family: 'Lobster', cursive; color: red; font-size: 50px;">
            'Product You entered is Not There'
        </h2>
        
        {% endblock body %}

    </body>
</html>


